// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDeliveries = `-- name: ClaimDeliveries :many
update delivery
set leased_until = now() + make_interval(secs => $1::float)
where id in (
    select id from delivery
    where state = 'pending'
      and next_attempt_at <= now()
      and (leased_until is null or leased_until <= now())
    order by next_attempt_at
    limit $2
    for update skip locked
)
returning id, event_id, destination_id, attempts, replay_count
`

type ClaimDeliveriesParams struct {
	LeaseSeconds float64
	BatchSize    int32
}

type ClaimDeliveriesRow struct {
	ID            uuid.UUID
	EventID       uuid.UUID
	DestinationID uuid.UUID
	Attempts      int32
	ReplayCount   int32
}

func (q *Queries) ClaimDeliveries(ctx context.Context, arg ClaimDeliveriesParams) ([]ClaimDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimDeliveries, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDeliveriesRow{}
	for rows.Next() {
		var i ClaimDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.DestinationID,
			&i.Attempts,
			&i.ReplayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimUnplannedEvents = `-- name: ClaimUnplannedEvents :many
select id, provider from inbound_event
where planned_at is null
order by received_at
limit $1
for update skip locked
`

type ClaimUnplannedEventsRow struct {
	ID       uuid.UUID
	Provider string
}

func (q *Queries) ClaimUnplannedEvents(ctx context.Context, limit int32) ([]ClaimUnplannedEventsRow, error) {
	rows, err := q.db.Query(ctx, claimUnplannedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimUnplannedEventsRow{}
	for rows.Next() {
		var i ClaimUnplannedEventsRow
		if err := rows.Scan(&i.ID, &i.Provider); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDeliveriesByState = `-- name: CountDeliveriesByState :many
select state, count(*) as total from delivery group by state order by state
`

type CountDeliveriesByStateRow struct {
	State string
	Total int64
}

func (q *Queries) CountDeliveriesByState(ctx context.Context) ([]CountDeliveriesByStateRow, error) {
	rows, err := q.db.Query(ctx, countDeliveriesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDeliveriesByStateRow{}
	for rows.Next() {
		var i CountDeliveriesByStateRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEventsAwaitingRoute = `-- name: CountEventsAwaitingRoute :one
select count(*) from inbound_event e
where e.planned_at is null
  and not exists (
      select 1 from route r
      join destination d on d.id = r.destination_id and d.enabled
      where r.provider = e.provider
  )
`

func (q *Queries) CountEventsAwaitingRoute(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsAwaitingRoute)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDelivery = `-- name: CreateDelivery :exec
insert into delivery (id, event_id, destination_id, state, next_attempt_at)
values ($1, $2, $3, 'pending', now())
on conflict (event_id, destination_id) do nothing
`

type CreateDeliveryParams struct {
	ID            uuid.UUID
	EventID       uuid.UUID
	DestinationID uuid.UUID
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) error {
	_, err := q.db.Exec(ctx, createDelivery, arg.ID, arg.EventID, arg.DestinationID)
	return err
}

const createDestination = `-- name: CreateDestination :one
insert into destination (id, name, url)
values ($1, $2, $3)
returning id, name, url, enabled, created_at
`

type CreateDestinationParams struct {
	ID   uuid.UUID
	Name string
	Url  string
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, createDestination, arg.ID, arg.Name, arg.Url)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const createRoute = `-- name: CreateRoute :exec
insert into route (id, provider, destination_id)
values ($1, $2, $3)
on conflict (provider, destination_id) do nothing
`

type CreateRouteParams struct {
	ID            uuid.UUID
	Provider      string
	DestinationID uuid.UUID
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) error {
	_, err := q.db.Exec(ctx, createRoute, arg.ID, arg.Provider, arg.DestinationID)
	return err
}

const deliveryTarget = `-- name: DeliveryTarget :one
select d.url, e.provider, e.path, r.headers, r.body
from delivery dl
join inbound_event e on e.id = dl.event_id
join inbound_request r on r.event_id = dl.event_id
join destination d on d.id = dl.destination_id
where dl.id = $1
`

type DeliveryTargetRow struct {
	Url      string
	Provider string
	Path     string
	Headers  []byte
	Body     []byte
}

func (q *Queries) DeliveryTarget(ctx context.Context, id uuid.UUID) (DeliveryTargetRow, error) {
	row := q.db.QueryRow(ctx, deliveryTarget, id)
	var i DeliveryTargetRow
	err := row.Scan(
		&i.Url,
		&i.Provider,
		&i.Path,
		&i.Headers,
		&i.Body,
	)
	return i, err
}

const destinationByName = `-- name: DestinationByName :one
select id, name, url, enabled, created_at from destination where name = $1
`

func (q *Queries) DestinationByName(ctx context.Context, name string) (Destination, error) {
	row := q.db.QueryRow(ctx, destinationByName, name)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const enabledDestinationsForProvider = `-- name: EnabledDestinationsForProvider :many
select d.id from route r
join destination d on d.id = r.destination_id
where r.provider = $1 and d.enabled
`

func (q *Queries) EnabledDestinationsForProvider(ctx context.Context, provider string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, enabledDestinationsForProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
select r.provider, d.name, d.url, d.enabled
from route r
join destination d on d.id = r.destination_id
order by r.provider, d.name
`

type ListRoutesRow struct {
	Provider string
	Name     string
	Url      string
	Enabled  bool
}

func (q *Queries) ListRoutes(ctx context.Context) ([]ListRoutesRow, error) {
	rows, err := q.db.Query(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutesRow{}
	for rows.Next() {
		var i ListRoutesRow
		if err := rows.Scan(
			&i.Provider,
			&i.Name,
			&i.Url,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDelivered = `-- name: MarkDelivered :exec
update delivery
set state = 'delivered',
    delivered_at = now(),
    attempts = attempts + 1,
    last_status = $2,
    last_error = null,
    leased_until = null
where id = $1
`

type MarkDeliveredParams struct {
	ID         uuid.UUID
	LastStatus pgtype.Int4
}

func (q *Queries) MarkDelivered(ctx context.Context, arg MarkDeliveredParams) error {
	_, err := q.db.Exec(ctx, markDelivered, arg.ID, arg.LastStatus)
	return err
}

const markEventPlanned = `-- name: MarkEventPlanned :exec
update inbound_event set planned_at = now() where id = $1
`

func (q *Queries) MarkEventPlanned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventPlanned, id)
	return err
}

const markFailed = `-- name: MarkFailed :exec
update delivery
set attempts = attempts + 1,
    next_attempt_at = $2,
    last_status = $3,
    last_error = $4,
    leased_until = null,
    state = case when attempts + 1 >= $5::int then 'dead' else 'pending' end
where id = $1
`

type MarkFailedParams struct {
	ID            uuid.UUID
	NextAttemptAt time.Time
	LastStatus    pgtype.Int4
	LastError     pgtype.Text
	MaxAttempts   int32
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.Exec(ctx, markFailed,
		arg.ID,
		arg.NextAttemptAt,
		arg.LastStatus,
		arg.LastError,
		arg.MaxAttempts,
	)
	return err
}

const nextWorkAt = `-- name: NextWorkAt :one
with next as (
    select least(
        (select min(next_attempt_at) from delivery where state = 'pending'),
        (select case when exists (
                    select 1 from inbound_event e
                    join route r on r.provider = e.provider
                    join destination d on d.id = r.destination_id and d.enabled
                    where e.planned_at is null
                ) then now() end)
    ) as at
)
select coalesce(at, now())::timestamptz as at,
       (at is not null)::boolean       as found
from next
`

type NextWorkAtRow struct {
	At    time.Time
	Found bool
}

func (q *Queries) NextWorkAt(ctx context.Context) (NextWorkAtRow, error) {
	row := q.db.QueryRow(ctx, nextWorkAt)
	var i NextWorkAtRow
	err := row.Scan(&i.At, &i.Found)
	return i, err
}

const notifyWork = `-- name: NotifyWork :exec
select pg_notify('charon_work', '')
`

func (q *Queries) NotifyWork(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyWork)
	return err
}

const oldestPendingAge = `-- name: OldestPendingAge :one
select coalesce(extract(epoch from now() - min(created_at)), 0)::float as seconds
from delivery where state = 'pending'
`

func (q *Queries) OldestPendingAge(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, oldestPendingAge)
	var seconds float64
	err := row.Scan(&seconds)
	return seconds, err
}
