// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbound.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countInboundEvents = `-- name: CountInboundEvents :one
select count(*) from inbound_event
`

func (q *Queries) CountInboundEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInboundEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInboundEvent = `-- name: CreateInboundEvent :exec
insert into inbound_event (
    id, provider, path, received_at, body_size
) values (
    $1, $2, $3, $4, $5
)
`

type CreateInboundEventParams struct {
	ID         uuid.UUID
	Provider   string
	Path       string
	ReceivedAt time.Time
	BodySize   int32
}

func (q *Queries) CreateInboundEvent(ctx context.Context, arg CreateInboundEventParams) error {
	_, err := q.db.Exec(ctx, createInboundEvent,
		arg.ID,
		arg.Provider,
		arg.Path,
		arg.ReceivedAt,
		arg.BodySize,
	)
	return err
}

const createInboundRequest = `-- name: CreateInboundRequest :exec
insert into inbound_request (
    event_id, headers, body
) values (
    $1, $2, $3
)
`

type CreateInboundRequestParams struct {
	EventID uuid.UUID
	Headers []byte
	Body    []byte
}

func (q *Queries) CreateInboundRequest(ctx context.Context, arg CreateInboundRequestParams) error {
	_, err := q.db.Exec(ctx, createInboundRequest, arg.EventID, arg.Headers, arg.Body)
	return err
}

const getInboundEvent = `-- name: GetInboundEvent :one
select id, provider, path, received_at, body_size from inbound_event where id = $1
`

func (q *Queries) GetInboundEvent(ctx context.Context, id uuid.UUID) (InboundEvent, error) {
	row := q.db.QueryRow(ctx, getInboundEvent, id)
	var i InboundEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Path,
		&i.ReceivedAt,
		&i.BodySize,
	)
	return i, err
}

const getInboundRequest = `-- name: GetInboundRequest :one
select event_id, headers, body from inbound_request where event_id = $1
`

func (q *Queries) GetInboundRequest(ctx context.Context, eventID uuid.UUID) (InboundRequest, error) {
	row := q.db.QueryRow(ctx, getInboundRequest, eventID)
	var i InboundRequest
	err := row.Scan(&i.EventID, &i.Headers, &i.Body)
	return i, err
}

const listRecentInboundEvents = `-- name: ListRecentInboundEvents :many
select id, provider, path, received_at, body_size from inbound_event order by received_at desc limit $1
`

func (q *Queries) ListRecentInboundEvents(ctx context.Context, limit int32) ([]InboundEvent, error) {
	rows, err := q.db.Query(ctx, listRecentInboundEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboundEvent{}
	for rows.Next() {
		var i InboundEvent
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Path,
			&i.ReceivedAt,
			&i.BodySize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
