// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const attemptTotals = `-- name: AttemptTotals :many
select t.slug, count(*) as total
from delivery_attempt a join tenant t on t.id = a.tenant_id
where a.tenant_id = $1
group by t.slug
`

type AttemptTotalsRow struct {
	Slug  string
	Total int64
}

func (q *Queries) AttemptTotals(ctx context.Context, tenantID uuid.UUID) ([]AttemptTotalsRow, error) {
	rows, err := q.db.Query(ctx, attemptTotals, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptTotalsRow{}
	for rows.Next() {
		var i AttemptTotalsRow
		if err := rows.Scan(&i.Slug, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOperators = `-- name: CountOperators :one
select count(*) from panel_user
`

func (q *Queries) CountOperators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOperators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deliveryTotals = `-- name: DeliveryTotals :many
select t.slug, d.state, count(*) as total
from delivery d join tenant t on t.id = d.tenant_id
where d.tenant_id = $1
group by t.slug, d.state
`

type DeliveryTotalsRow struct {
	Slug  string
	State string
	Total int64
}

func (q *Queries) DeliveryTotals(ctx context.Context, tenantID uuid.UUID) ([]DeliveryTotalsRow, error) {
	rows, err := q.db.Query(ctx, deliveryTotals, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryTotalsRow{}
	for rows.Next() {
		var i DeliveryTotalsRow
		if err := rows.Scan(&i.Slug, &i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventTotals = `-- name: EventTotals :many

select t.slug, e.signature, count(*) as total
from inbound_event e join tenant t on t.id = e.tenant_id
where e.tenant_id = $1
group by t.slug, e.signature
`

type EventTotalsRow struct {
	Slug      string
	Signature string
	Total     int64
}

// Every number a scrape reports, one tenant at a time. A scrape covers the
// whole deployment, but each query still names the tenant it counts: the
// tenant is pinned on the connection, not on the statement, so a query that
// left it out would count whatever the pooled connection happened to be
// pinned to and report it under every tenant's name.
func (q *Queries) EventTotals(ctx context.Context, tenantID uuid.UUID) ([]EventTotalsRow, error) {
	rows, err := q.db.Query(ctx, eventTotals, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTotalsRow{}
	for rows.Next() {
		var i EventTotalsRow
		if err := rows.Scan(&i.Slug, &i.Signature, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestPending = `-- name: OldestPending :many
select t.slug, coalesce(extract(epoch from now() - min(d.next_attempt_at)), 0)::float8 as seconds
from delivery d join tenant t on t.id = d.tenant_id
where d.state = 'pending' and d.tenant_id = $1
group by t.slug
`

type OldestPendingRow struct {
	Slug    string
	Seconds float64
}

func (q *Queries) OldestPending(ctx context.Context, tenantID uuid.UUID) ([]OldestPendingRow, error) {
	rows, err := q.db.Query(ctx, oldestPending, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OldestPendingRow{}
	for rows.Next() {
		var i OldestPendingRow
		if err := rows.Scan(&i.Slug, &i.Seconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
