// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthMethod struct {
	Name        string
	Description string
}

type ClaimPlacement struct {
	Method    string
	Value     string
	TenantID  uuid.UUID
	RoleID    pgtype.UUID
	CreatedAt time.Time
}

type Delivery struct {
	ID            uuid.UUID
	EventID       uuid.UUID
	DestinationID uuid.UUID
	State         string
	Attempts      int32
	NextAttemptAt time.Time
	LeasedUntil   pgtype.Timestamptz
	LastStatus    pgtype.Int4
	LastError     pgtype.Text
	DeliveredAt   pgtype.Timestamptz
	CreatedAt     time.Time
	ReplayCount   int32
	ReplayedAt    pgtype.Timestamptz
	TenantID      uuid.UUID
}

type DeliveryAttempt struct {
	ID                uuid.UUID
	DeliveryID        uuid.UUID
	Attempt           int32
	AttemptedAt       time.Time
	Status            pgtype.Int4
	Error             pgtype.Text
	DurationMs        int32
	Round             int32
	TenantID          uuid.UUID
	SignedWith        string
	Forced            bool
	Response          []byte
	ResponseType      string
	ResponseTruncated bool
}

type DeliveryState struct {
	Name        string
	Description string
}

type Destination struct {
	ID        uuid.UUID
	Name      string
	Url       string
	Enabled   bool
	CreatedAt time.Time
	Transport string
	TenantID  uuid.UUID
}

type InboundEvent struct {
	ID         uuid.UUID
	Provider   string
	Path       string
	ReceivedAt time.Time
	BodySize   int32
	PlannedAt  pgtype.Timestamptz
	Signature  string
	TenantID   uuid.UUID
	OverrideID pgtype.UUID
}

type InboundRequest struct {
	EventID  uuid.UUID
	Headers  []byte
	Body     []byte
	TenantID uuid.UUID
}

type Membership struct {
	UserID    uuid.UUID
	TenantID  uuid.UUID
	RoleID    pgtype.UUID
	CreatedAt time.Time
}

type PanelSession struct {
	Token     []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type PanelUser struct {
	ID           uuid.UUID
	Email        string
	PasswordHash pgtype.Text
	CreatedAt    time.Time
	OidcSubject  pgtype.Text
	SystemAdmin  bool
	TimeZone     string
}

type Permission struct {
	ID          uuid.UUID
	Name        string
	Description string
}

type Provider struct {
	Name             string
	Verifier         string
	SecretEnv        string
	SignatureHeader  pgtype.Text
	ToleranceSeconds int32
	CreatedAt        time.Time
	Scheme           string
	Algorithm        string
	Encoding         string
	TimestampKey     string
	SignatureKey     string
	TenantID         uuid.UUID
	VerifyTokenEnv   string
}

type Role struct {
	TenantID    pgtype.UUID
	Name        string
	Description string
	BuiltIn     bool
	CreatedAt   time.Time
	ID          uuid.UUID
	Changed     bool
}

type RoleGrant struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type Route struct {
	ID            uuid.UUID
	Provider      string
	DestinationID uuid.UUID
	CreatedAt     time.Time
	TenantID      uuid.UUID
}

type SchemaMigration struct {
	Name      string
	AppliedAt time.Time
}

type SignatureOverride struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Reason    string
	DecidedBy uuid.UUID
	DecidedAt time.Time
}

type SignatureState struct {
	Name        string
	Description string
}

type SigningSecret struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	DestinationID uuid.UUID
	Reference     string
	CreatedAt     time.Time
}

type SigningSecretCheck struct {
	SigningSecretID uuid.UUID
	TenantID        uuid.UUID
	Readable        bool
	Detail          string
	CheckedAt       time.Time
}

type Tenant struct {
	ID            uuid.UUID
	Slug          string
	Name          string
	CreatedAt     time.Time
	RetentionDays pgtype.Int4
}

type Transport struct {
	Name        string
	Description string
}

type Verifier struct {
	Name        string
	Description string
}
