// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: panel.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPanelUsers = `-- name: CountPanelUsers :one
select count(*) from panel_user
`

func (q *Queries) CountPanelUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPanelUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPanelSession = `-- name: CreatePanelSession :exec
insert into panel_session (token, user_id, expires_at)
values ($1, $2, $3)
`

type CreatePanelSessionParams struct {
	Token     []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreatePanelSession(ctx context.Context, arg CreatePanelSessionParams) error {
	_, err := q.db.Exec(ctx, createPanelSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createPanelUser = `-- name: CreatePanelUser :exec
insert into panel_user (id, email, password_hash)
values ($1, $2, $3)
`

type CreatePanelUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash pgtype.Text
}

func (q *Queries) CreatePanelUser(ctx context.Context, arg CreatePanelUserParams) error {
	_, err := q.db.Exec(ctx, createPanelUser, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const createSSOUser = `-- name: CreateSSOUser :one
insert into panel_user (id, email, oidc_subject)
values ($1, $2, $3)
returning id, email, password_hash, created_at, oidc_subject
`

type CreateSSOUserParams struct {
	ID          uuid.UUID
	Email       string
	OidcSubject pgtype.Text
}

func (q *Queries) CreateSSOUser(ctx context.Context, arg CreateSSOUserParams) (PanelUser, error) {
	row := q.db.QueryRow(ctx, createSSOUser, arg.ID, arg.Email, arg.OidcSubject)
	var i PanelUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OidcSubject,
	)
	return i, err
}

const deleteExpiredPanelSessions = `-- name: DeleteExpiredPanelSessions :exec
delete from panel_session where expires_at <= now()
`

func (q *Queries) DeleteExpiredPanelSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPanelSessions)
	return err
}

const deletePanelSession = `-- name: DeletePanelSession :exec
delete from panel_session where token = $1
`

func (q *Queries) DeletePanelSession(ctx context.Context, token []byte) error {
	_, err := q.db.Exec(ctx, deletePanelSession, token)
	return err
}

const deleteRoute = `-- name: DeleteRoute :exec
delete from route where id = $1
`

func (q *Queries) DeleteRoute(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoute, id)
	return err
}

const deliveryAttempts = `-- name: DeliveryAttempts :many
select round, attempt, attempted_at, status, error, duration_ms
from delivery_attempt
where delivery_id = $1
order by round desc, attempted_at desc
`

type DeliveryAttemptsRow struct {
	Round       int32
	Attempt     int32
	AttemptedAt time.Time
	Status      pgtype.Int4
	Error       pgtype.Text
	DurationMs  int32
}

func (q *Queries) DeliveryAttempts(ctx context.Context, deliveryID uuid.UUID) ([]DeliveryAttemptsRow, error) {
	rows, err := q.db.Query(ctx, deliveryAttempts, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAttemptsRow{}
	for rows.Next() {
		var i DeliveryAttemptsRow
		if err := rows.Scan(
			&i.Round,
			&i.Attempt,
			&i.AttemptedAt,
			&i.Status,
			&i.Error,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deliveryStateTotals = `-- name: DeliveryStateTotals :many
select state, count(*) as total from delivery group by state
`

type DeliveryStateTotalsRow struct {
	State string
	Total int64
}

func (q *Queries) DeliveryStateTotals(ctx context.Context) ([]DeliveryStateTotalsRow, error) {
	rows, err := q.db.Query(ctx, deliveryStateTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryStateTotalsRow{}
	for rows.Next() {
		var i DeliveryStateTotalsRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const detailedRoutes = `-- name: DetailedRoutes :many
select r.id, r.provider, d.id as destination_id, d.name, d.url, d.enabled,
       (select count(*) from delivery dl where dl.destination_id = d.id)::bigint as deliveries
from route r
join destination d on d.id = r.destination_id
order by r.provider, d.name
`

type DetailedRoutesRow struct {
	ID            uuid.UUID
	Provider      string
	DestinationID uuid.UUID
	Name          string
	Url           string
	Enabled       bool
	Deliveries    int64
}

func (q *Queries) DetailedRoutes(ctx context.Context) ([]DetailedRoutesRow, error) {
	rows, err := q.db.Query(ctx, detailedRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetailedRoutesRow{}
	for rows.Next() {
		var i DetailedRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.DestinationID,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.Deliveries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const distinctProviders = `-- name: DistinctProviders :many
select distinct provider from inbound_event order by provider
`

func (q *Queries) DistinctProviders(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, distinctProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventDeliveries = `-- name: EventDeliveries :many
select d.id, dest.name as destination, dest.url, d.state, d.attempts,
       d.next_attempt_at, d.last_status, d.last_error, d.delivered_at,
       d.replay_count, d.replayed_at,
       exists (
           select 1
           from inbound_event e
           join route r on r.provider = e.provider
           join destination active on active.id = r.destination_id and active.enabled
           where e.id = d.event_id and r.destination_id = d.destination_id
       )::boolean as routed
from delivery d
join destination dest on dest.id = d.destination_id
where d.event_id = $1
order by dest.name
`

type EventDeliveriesRow struct {
	ID            uuid.UUID
	Destination   string
	Url           string
	State         string
	Attempts      int32
	NextAttemptAt time.Time
	LastStatus    pgtype.Int4
	LastError     pgtype.Text
	DeliveredAt   pgtype.Timestamptz
	ReplayCount   int32
	ReplayedAt    pgtype.Timestamptz
	Routed        bool
}

func (q *Queries) EventDeliveries(ctx context.Context, eventID uuid.UUID) ([]EventDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, eventDeliveries, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDeliveriesRow{}
	for rows.Next() {
		var i EventDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Destination,
			&i.Url,
			&i.State,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastStatus,
			&i.LastError,
			&i.DeliveredAt,
			&i.ReplayCount,
			&i.ReplayedAt,
			&i.Routed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventDetail = `-- name: EventDetail :one
select e.id, e.provider, e.path, e.received_at, e.body_size, e.planned_at,
       r.headers, r.body
from inbound_event e
join inbound_request r on r.event_id = e.id
where e.id = $1
`

type EventDetailRow struct {
	ID         uuid.UUID
	Provider   string
	Path       string
	ReceivedAt time.Time
	BodySize   int32
	PlannedAt  pgtype.Timestamptz
	Headers    []byte
	Body       []byte
}

func (q *Queries) EventDetail(ctx context.Context, id uuid.UUID) (EventDetailRow, error) {
	row := q.db.QueryRow(ctx, eventDetail, id)
	var i EventDetailRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Path,
		&i.ReceivedAt,
		&i.BodySize,
		&i.PlannedAt,
		&i.Headers,
		&i.Body,
	)
	return i, err
}

const linkSubjectToUser = `-- name: LinkSubjectToUser :one
update panel_user set oidc_subject = $2 where email = $1 returning id, email, password_hash, created_at, oidc_subject
`

type LinkSubjectToUserParams struct {
	Email       string
	OidcSubject pgtype.Text
}

func (q *Queries) LinkSubjectToUser(ctx context.Context, arg LinkSubjectToUserParams) (PanelUser, error) {
	row := q.db.QueryRow(ctx, linkSubjectToUser, arg.Email, arg.OidcSubject)
	var i PanelUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OidcSubject,
	)
	return i, err
}

const notifyPanel = `-- name: NotifyPanel :exec
select pg_notify('charon_panel', '')
`

func (q *Queries) NotifyPanel(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyPanel)
	return err
}

const panelSessionUser = `-- name: PanelSessionUser :one
select u.id, u.email
from panel_session s
join panel_user u on u.id = s.user_id
where s.token = $1 and s.expires_at > now()
`

type PanelSessionUserRow struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) PanelSessionUser(ctx context.Context, token []byte) (PanelSessionUserRow, error) {
	row := q.db.QueryRow(ctx, panelSessionUser, token)
	var i PanelSessionUserRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const panelUserByEmail = `-- name: PanelUserByEmail :one
select id, email, password_hash, created_at, oidc_subject from panel_user where email = $1
`

func (q *Queries) PanelUserByEmail(ctx context.Context, email string) (PanelUser, error) {
	row := q.db.QueryRow(ctx, panelUserByEmail, email)
	var i PanelUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OidcSubject,
	)
	return i, err
}

const panelUserBySubject = `-- name: PanelUserBySubject :one
select id, email, password_hash, created_at, oidc_subject from panel_user where oidc_subject = $1
`

func (q *Queries) PanelUserBySubject(ctx context.Context, oidcSubject pgtype.Text) (PanelUser, error) {
	row := q.db.QueryRow(ctx, panelUserBySubject, oidcSubject)
	var i PanelUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OidcSubject,
	)
	return i, err
}

const providerAlreadyRoutedTo = `-- name: ProviderAlreadyRoutedTo :one
select exists (
    select 1 from route r
    join destination d on d.id = r.destination_id
    where r.provider = $1 and d.url = $2
)::boolean as taken
`

type ProviderAlreadyRoutedToParams struct {
	Provider string
	Url      string
}

func (q *Queries) ProviderAlreadyRoutedTo(ctx context.Context, arg ProviderAlreadyRoutedToParams) (bool, error) {
	row := q.db.QueryRow(ctx, providerAlreadyRoutedTo, arg.Provider, arg.Url)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const recordDeliveryAttempt = `-- name: RecordDeliveryAttempt :exec
insert into delivery_attempt (id, delivery_id, attempt, round, status, error, duration_ms)
select $1, $2, $3, d.replay_count, $4, $5, $6
from delivery d
where d.id = $2
`

type RecordDeliveryAttemptParams struct {
	ID         uuid.UUID
	DeliveryID uuid.UUID
	Attempt    int32
	Status     pgtype.Int4
	Error      pgtype.Text
	DurationMs int32
}

func (q *Queries) RecordDeliveryAttempt(ctx context.Context, arg RecordDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, recordDeliveryAttempt,
		arg.ID,
		arg.DeliveryID,
		arg.Attempt,
		arg.Status,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const replayDelivery = `-- name: ReplayDelivery :execrows

update delivery as dl
set state = 'pending',
    attempts = 0,
    next_attempt_at = now(),
    leased_until = null,
    last_status = null,
    last_error = null,
    delivered_at = null,
    replay_count = replay_count + 1,
    replayed_at = now()
where dl.id = $1
  and exists (
      select 1
      from inbound_event e
      join route r on r.provider = e.provider
      join destination dst on dst.id = r.destination_id and dst.enabled
      where e.id = dl.event_id and r.destination_id = dl.destination_id
  )
`

// A replay only reopens deliveries whose destination is still routed for this
// event's provider and still enabled. Anything else is history: the routes page
// is the truth about where events go.
func (q *Queries) ReplayDelivery(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, replayDelivery, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replayDestination = `-- name: ReplayDestination :execrows
update delivery as dl
set state = 'pending',
    attempts = 0,
    next_attempt_at = now(),
    leased_until = null,
    last_status = null,
    last_error = null,
    delivered_at = null,
    replay_count = replay_count + 1,
    replayed_at = now()
where dl.destination_id = $1
  and exists (
      select 1
      from inbound_event e
      join route r on r.provider = e.provider
      join destination dst on dst.id = r.destination_id and dst.enabled
      where e.id = dl.event_id and r.destination_id = dl.destination_id
  )
`

func (q *Queries) ReplayDestination(ctx context.Context, destinationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, replayDestination, destinationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replayEvent = `-- name: ReplayEvent :execrows
update delivery as dl
set state = 'pending',
    attempts = 0,
    next_attempt_at = now(),
    leased_until = null,
    last_status = null,
    last_error = null,
    delivered_at = null,
    replay_count = replay_count + 1,
    replayed_at = now()
where dl.event_id = $1
  and exists (
      select 1
      from inbound_event e
      join route r on r.provider = e.provider
      join destination dst on dst.id = r.destination_id and dst.enabled
      where e.id = dl.event_id and r.destination_id = dl.destination_id
  )
`

func (q *Queries) ReplayEvent(ctx context.Context, eventID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, replayEvent, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const routeByID = `-- name: RouteByID :one
select r.id, r.provider, d.id as destination_id, d.name, d.enabled
from route r join destination d on d.id = r.destination_id
where r.id = $1
`

type RouteByIDRow struct {
	ID            uuid.UUID
	Provider      string
	DestinationID uuid.UUID
	Name          string
	Enabled       bool
}

func (q *Queries) RouteByID(ctx context.Context, id uuid.UUID) (RouteByIDRow, error) {
	row := q.db.QueryRow(ctx, routeByID, id)
	var i RouteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.DestinationID,
		&i.Name,
		&i.Enabled,
	)
	return i, err
}

const searchEvents = `-- name: SearchEvents :many
select e.id, e.provider, e.path, e.received_at, e.body_size,
       (e.planned_at is not null)::boolean as planned,
       coalesce((select count(*) from delivery d where d.event_id = e.id
                 and routed(e.provider, d.destination_id)), 0)::bigint as deliveries,
       coalesce((select count(*) from delivery d where d.event_id = e.id and d.state = 'delivered'
                 and routed(e.provider, d.destination_id)), 0)::bigint as delivered,
       coalesce((select count(*) from delivery d where d.event_id = e.id and d.state = 'dead'
                 and routed(e.provider, d.destination_id)), 0)::bigint as dead,
       coalesce((select count(*) from delivery d where d.event_id = e.id and d.state = 'pending'
                 and routed(e.provider, d.destination_id)), 0)::bigint as pending,
       coalesce((select count(*) from delivery d where d.event_id = e.id
                 and not routed(e.provider, d.destination_id)), 0)::bigint as unrouted,
       coalesce((select max(d.attempts) from delivery d where d.event_id = e.id
                 and routed(e.provider, d.destination_id)), 0)::int as attempts
from inbound_event e
where ($1::text is null or e.provider = $1::text)
  and ($2::timestamptz is null or e.received_at >= $2::timestamptz)
  and ($3::timestamptz is null or e.received_at <= $3::timestamptz)
  and (
       $4::text is null
       or ($4::text = 'unrouted' and not exists (
               select 1 from delivery d
               where d.event_id = e.id and routed(e.provider, d.destination_id)))
       or ($4::text <> 'unrouted' and exists (
               select 1 from delivery d
               where d.event_id = e.id
                 and d.state = $4::text
                 and routed(e.provider, d.destination_id)))
  )
  and ($5::text is null
       or e.id::text = $5::text
       or position($5::text in convert_from(
              (select r.body from inbound_request r where r.event_id = e.id), 'UTF8')) > 0)
order by e.received_at desc
limit $7 offset $6
`

type SearchEventsParams struct {
	Provider   pgtype.Text
	Since      pgtype.Timestamptz
	Until      pgtype.Timestamptz
	State      pgtype.Text
	Search     pgtype.Text
	PageOffset int32
	PageSize   int32
}

type SearchEventsRow struct {
	ID         uuid.UUID
	Provider   string
	Path       string
	ReceivedAt time.Time
	BodySize   int32
	Planned    bool
	Deliveries int64
	Delivered  int64
	Dead       int64
	Pending    int64
	Unrouted   int64
	Attempts   int32
}

// The state counts only take deliveries whose destination is still routed and
// enabled, so the numbers reconcile with the routes page. What is left over is
// reported apart as history.
func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]SearchEventsRow, error) {
	rows, err := q.db.Query(ctx, searchEvents,
		arg.Provider,
		arg.Since,
		arg.Until,
		arg.State,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEventsRow{}
	for rows.Next() {
		var i SearchEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Path,
			&i.ReceivedAt,
			&i.BodySize,
			&i.Planned,
			&i.Deliveries,
			&i.Delivered,
			&i.Dead,
			&i.Pending,
			&i.Unrouted,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unplanEvent = `-- name: UnplanEvent :exec
update inbound_event set planned_at = null where id = $1
`

func (q *Queries) UnplanEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unplanEvent, id)
	return err
}

const unplanProvider = `-- name: UnplanProvider :execrows
update inbound_event set planned_at = null where provider = $1
`

func (q *Queries) UnplanProvider(ctx context.Context, provider string) (int64, error) {
	result, err := q.db.Exec(ctx, unplanProvider, provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unroutedProviders = `-- name: UnroutedProviders :many
select e.provider,
       count(*)::bigint    as events,
       max(e.received_at)::timestamptz as last_received
from inbound_event e
where not exists (select 1 from route r where r.provider = e.provider)
group by e.provider
order by max(e.received_at) desc
`

type UnroutedProvidersRow struct {
	Provider     string
	Events       int64
	LastReceived time.Time
}

func (q *Queries) UnroutedProviders(ctx context.Context) ([]UnroutedProvidersRow, error) {
	rows, err := q.db.Query(ctx, unroutedProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnroutedProvidersRow{}
	for rows.Next() {
		var i UnroutedProvidersRow
		if err := rows.Scan(&i.Provider, &i.Events, &i.LastReceived); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestination = `-- name: UpdateDestination :exec
update destination set url = $2, enabled = $3 where id = $1
`

type UpdateDestinationParams struct {
	ID      uuid.UUID
	Url     string
	Enabled bool
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) error {
	_, err := q.db.Exec(ctx, updateDestination, arg.ID, arg.Url, arg.Enabled)
	return err
}
