// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProvider = `-- name: DeleteProvider :exec
delete from provider where tenant_id = $1 and name = $2
`

type DeleteProviderParams struct {
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) DeleteProvider(ctx context.Context, arg DeleteProviderParams) error {
	_, err := q.db.Exec(ctx, deleteProvider, arg.TenantID, arg.Name)
	return err
}

const knownProviders = `-- name: KnownProviders :many
select p.name from provider p where p.tenant_id = $1
union
select e.provider from inbound_event e where e.tenant_id = $1
union
select r.provider from route r where r.tenant_id = $1
order by 1
`

func (q *Queries) KnownProviders(ctx context.Context, tenantID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, knownProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSignature = `-- name: MarkSignature :exec
update inbound_event set signature = $2 where id = $1
`

type MarkSignatureParams struct {
	ID        uuid.UUID
	Signature string
}

func (q *Queries) MarkSignature(ctx context.Context, arg MarkSignatureParams) error {
	_, err := q.db.Exec(ctx, markSignature, arg.ID, arg.Signature)
	return err
}

const markSignatureAndReopen = `-- name: MarkSignatureAndReopen :exec
update inbound_event set signature = $2, planned_at = null where id = $1
`

type MarkSignatureAndReopenParams struct {
	ID        uuid.UUID
	Signature string
}

func (q *Queries) MarkSignatureAndReopen(ctx context.Context, arg MarkSignatureAndReopenParams) error {
	_, err := q.db.Exec(ctx, markSignatureAndReopen, arg.ID, arg.Signature)
	return err
}

const notifyProviders = `-- name: NotifyProviders :exec
select pg_notify('charon_provider', '')
`

func (q *Queries) NotifyProviders(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyProviders)
	return err
}

const providers = `-- name: Providers :many
select name, verifier, secret_env, signature_header, tolerance_seconds,
       scheme, algorithm, encoding, timestamp_key, signature_key
from provider where tenant_id = $1 order by name
`

type ProvidersRow struct {
	Name             string
	Verifier         string
	SecretEnv        string
	SignatureHeader  pgtype.Text
	ToleranceSeconds int32
	Scheme           string
	Algorithm        string
	Encoding         string
	TimestampKey     string
	SignatureKey     string
}

func (q *Queries) Providers(ctx context.Context, tenantID uuid.UUID) ([]ProvidersRow, error) {
	rows, err := q.db.Query(ctx, providers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvidersRow{}
	for rows.Next() {
		var i ProvidersRow
		if err := rows.Scan(
			&i.Name,
			&i.Verifier,
			&i.SecretEnv,
			&i.SignatureHeader,
			&i.ToleranceSeconds,
			&i.Scheme,
			&i.Algorithm,
			&i.Encoding,
			&i.TimestampKey,
			&i.SignatureKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refusedByProvider = `-- name: RefusedByProvider :many
select provider, count(*)::bigint as refused
from inbound_event
where tenant_id = $1 and signature in ('invalid', 'missing')
group by provider
`

type RefusedByProviderRow struct {
	Provider string
	Refused  int64
}

func (q *Queries) RefusedByProvider(ctx context.Context, tenantID uuid.UUID) ([]RefusedByProviderRow, error) {
	rows, err := q.db.Query(ctx, refusedByProvider, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefusedByProviderRow{}
	for rows.Next() {
		var i RefusedByProviderRow
		if err := rows.Scan(&i.Provider, &i.Refused); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProvider = `-- name: SetProvider :exec
insert into provider (
    tenant_id, name, verifier, secret_env, signature_header, tolerance_seconds,
    scheme, algorithm, encoding, timestamp_key, signature_key
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
on conflict (tenant_id, name) do update
set verifier = excluded.verifier,
    secret_env = excluded.secret_env,
    signature_header = excluded.signature_header,
    tolerance_seconds = excluded.tolerance_seconds,
    scheme = excluded.scheme,
    algorithm = excluded.algorithm,
    encoding = excluded.encoding,
    timestamp_key = excluded.timestamp_key,
    signature_key = excluded.signature_key
`

type SetProviderParams struct {
	TenantID         uuid.UUID
	Name             string
	Verifier         string
	SecretEnv        string
	SignatureHeader  pgtype.Text
	ToleranceSeconds int32
	Scheme           string
	Algorithm        string
	Encoding         string
	TimestampKey     string
	SignatureKey     string
}

func (q *Queries) SetProvider(ctx context.Context, arg SetProviderParams) error {
	_, err := q.db.Exec(ctx, setProvider,
		arg.TenantID,
		arg.Name,
		arg.Verifier,
		arg.SecretEnv,
		arg.SignatureHeader,
		arg.ToleranceSeconds,
		arg.Scheme,
		arg.Algorithm,
		arg.Encoding,
		arg.TimestampKey,
		arg.SignatureKey,
	)
	return err
}

const signatureTotals = `-- name: SignatureTotals :many
select signature, count(*)::bigint as total from inbound_event group by signature
`

type SignatureTotalsRow struct {
	Signature string
	Total     int64
}

func (q *Queries) SignatureTotals(ctx context.Context) ([]SignatureTotalsRow, error) {
	rows, err := q.db.Query(ctx, signatureTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignatureTotalsRow{}
	for rows.Next() {
		var i SignatureTotalsRow
		if err := rows.Scan(&i.Signature, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unverifiedEvents = `-- name: UnverifiedEvents :many
select e.id, e.provider, r.headers, r.body
from inbound_event e
join inbound_request r on r.event_id = e.id
where e.tenant_id = $1 and e.provider = $2 and e.signature in ('invalid', 'missing')
order by e.received_at
limit $3
`

type UnverifiedEventsParams struct {
	TenantID uuid.UUID
	Provider string
	Limit    int32
}

type UnverifiedEventsRow struct {
	ID       uuid.UUID
	Provider string
	Headers  []byte
	Body     []byte
}

func (q *Queries) UnverifiedEvents(ctx context.Context, arg UnverifiedEventsParams) ([]UnverifiedEventsRow, error) {
	rows, err := q.db.Query(ctx, unverifiedEvents, arg.TenantID, arg.Provider, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnverifiedEventsRow{}
	for rows.Next() {
		var i UnverifiedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Headers,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
