// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddSigningSecret(ctx context.Context, arg AddSigningSecretParams) error
	AttemptTotals(ctx context.Context, tenantID uuid.UUID) ([]AttemptTotalsRow, error)
	ClaimDeliveries(ctx context.Context, arg ClaimDeliveriesParams) ([]ClaimDeliveriesRow, error)
	// A signature that was checked and failed is never delivered, unless somebody
	// overruled that deliberately and said why. One that was never checked is
	// delivered: a provider with no verifier configured behaves as before.
	ClaimUnplannedEvents(ctx context.Context, limit int32) ([]ClaimUnplannedEventsRow, error)
	ClearRoleGrants(ctx context.Context, roleID uuid.UUID) error
	ClearSystemAdmin(ctx context.Context, id uuid.UUID) (int64, error)
	ClearSystemAdminByEmail(ctx context.Context, email string) (int64, error)
	CountEventsAwaitingRoute(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountInboundEvents(ctx context.Context) (int64, error)
	CountOperators(ctx context.Context) (int64, error)
	CountPanelUsers(ctx context.Context) (int64, error)
	CountSystemAdmins(ctx context.Context) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) error
	CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error)
	CreateInboundEvent(ctx context.Context, arg CreateInboundEventParams) (uuid.UUID, error)
	CreateInboundRequest(ctx context.Context, arg CreateInboundRequestParams) error
	CreatePanelSession(ctx context.Context, arg CreatePanelSessionParams) error
	CreatePanelUser(ctx context.Context, arg CreatePanelUserParams) (uuid.UUID, error)
	CreateRoute(ctx context.Context, arg CreateRouteParams) error
	CreateSSOUser(ctx context.Context, arg CreateSSOUserParams) (PanelUser, error)
	CreateSystemAdmin(ctx context.Context, arg CreateSystemAdminParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteExpiredPanelSessions(ctx context.Context) error
	DeletePanelSession(ctx context.Context, token []byte) error
	DeletePanelUser(ctx context.Context, arg DeletePanelUserParams) (int64, error)
	DeleteProvider(ctx context.Context, arg DeleteProviderParams) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error)
	DeleteRoute(ctx context.Context, arg DeleteRouteParams) error
	DeleteTenant(ctx context.Context, slug string) error
	DeliveryAttempts(ctx context.Context, arg DeliveryAttemptsParams) ([]DeliveryAttemptsRow, error)
	DeliveryStateTotals(ctx context.Context, tenantID uuid.UUID) ([]DeliveryStateTotalsRow, error)
	DeliveryTarget(ctx context.Context, id uuid.UUID) (DeliveryTargetRow, error)
	DeliveryTotals(ctx context.Context, tenantID uuid.UUID) ([]DeliveryTotalsRow, error)
	DestinationByName(ctx context.Context, arg DestinationByNameParams) (Destination, error)
	DestinationsWithoutSigning(ctx context.Context, tenantID uuid.UUID) ([]DestinationsWithoutSigningRow, error)
	DetailedRoutes(ctx context.Context, tenantID uuid.UUID) ([]DetailedRoutesRow, error)
	DistinctProviders(ctx context.Context, tenantID uuid.UUID) ([]string, error)
	EnabledDestinationsForProvider(ctx context.Context, arg EnabledDestinationsForProviderParams) ([]uuid.UUID, error)
	EventDeliveries(ctx context.Context, arg EventDeliveriesParams) ([]EventDeliveriesRow, error)
	EventDetail(ctx context.Context, arg EventDetailParams) (EventDetailRow, error)
	// Every number a scrape reports, one tenant at a time. A scrape covers the
	// whole deployment, but each query still names the tenant it counts: the
	// tenant is pinned on the connection, not on the statement, so a query that
	// left it out would count whatever the pooled connection happened to be
	// pinned to and report it under every tenant's name.
	EventTotals(ctx context.Context, tenantID uuid.UUID) ([]EventTotalsRow, error)
	EventsUnderOverride(ctx context.Context, overrideID pgtype.UUID) ([]uuid.UUID, error)
	GetInboundEvent(ctx context.Context, arg GetInboundEventParams) (InboundEvent, error)
	GetInboundRequest(ctx context.Context, arg GetInboundRequestParams) (InboundRequest, error)
	GrantPermission(ctx context.Context, arg GrantPermissionParams) error
	// A value that names only a tenant leaves the role to whoever decides it here,
	// so arriving again does not undo it.
	JoinFromProvider(ctx context.Context, arg JoinFromProviderParams) error
	// A value that names the role too makes the token the truth about it as well.
	JoinFromProviderAs(ctx context.Context, arg JoinFromProviderAsParams) error
	JoinTenant(ctx context.Context, arg JoinTenantParams) error
	KnownProviders(ctx context.Context, tenantID uuid.UUID) ([]string, error)
	LeaveEveryTenant(ctx context.Context, userID uuid.UUID) error
	LeaveEveryTenantByEmail(ctx context.Context, email string) error
	LeaveTenantsNoLongerNamed(ctx context.Context, arg LeaveTenantsNoLongerNamedParams) error
	LinkSubjectToUser(ctx context.Context, arg LinkSubjectToUserParams) (PanelUser, error)
	ListRecentInboundEvents(ctx context.Context, limit int32) ([]InboundEvent, error)
	ListRoutes(ctx context.Context, tenantID uuid.UUID) ([]ListRoutesRow, error)
	MarkDelivered(ctx context.Context, arg MarkDeliveredParams) error
	MarkEventPlanned(ctx context.Context, id uuid.UUID) error
	MarkFailed(ctx context.Context, arg MarkFailedParams) error
	MarkSignature(ctx context.Context, arg MarkSignatureParams) error
	MarkSignatureAndReopen(ctx context.Context, arg MarkSignatureAndReopenParams) error
	MembershipIn(ctx context.Context, arg MembershipInParams) (string, error)
	Memberships(ctx context.Context, userID uuid.UUID) ([]MembershipsRow, error)
	NextWorkAt(ctx context.Context) (NextWorkAtRow, error)
	NotifyPanel(ctx context.Context) error
	NotifyProviders(ctx context.Context) error
	NotifySigning(ctx context.Context) error
	NotifyTenants(ctx context.Context) error
	NotifyWork(ctx context.Context) error
	OldestPending(ctx context.Context, tenantID uuid.UUID) ([]OldestPendingRow, error)
	OldestPendingAge(ctx context.Context) (float64, error)
	// An event is overruled once. Saying so twice is the same decision, not a new
	// one, and the first is the one that let it out.
	OverrideEvents(ctx context.Context, arg OverrideEventsParams) (int64, error)
	OverruleOnEvent(ctx context.Context, arg OverruleOnEventParams) (OverruleOnEventRow, error)
	PanelSessionUser(ctx context.Context, token []byte) (PanelSessionUserRow, error)
	PanelUserByEmail(ctx context.Context, email string) (PanelUser, error)
	PanelUserBySubject(ctx context.Context, oidcSubject pgtype.Text) (PanelUser, error)
	PanelUsers(ctx context.Context, tenantID uuid.UUID) ([]PanelUsersRow, error)
	Permissions(ctx context.Context) ([]PermissionsRow, error)
	PlacementsPointedAt(ctx context.Context, arg PlacementsPointedAtParams) ([]PlacementsPointedAtRow, error)
	PointValueAt(ctx context.Context, arg PointValueAtParams) error
	ProviderAlreadyRoutedTo(ctx context.Context, arg ProviderAlreadyRoutedToParams) (bool, error)
	Providers(ctx context.Context, tenantID uuid.UUID) ([]ProvidersRow, error)
	// An event is only discarded once nothing is still trying to deliver it. A
	// pending delivery is live work, and its age says the destination has been
	// unreachable for a long time, which is a reason to look rather than to erase.
	PurgeEvents(ctx context.Context, arg PurgeEventsParams) (int64, error)
	PurgeableEvents(ctx context.Context, arg PurgeableEventsParams) (int64, error)
	RecordDeliveryAttempt(ctx context.Context, arg RecordDeliveryAttemptParams) error
	RecordOverride(ctx context.Context, arg RecordOverrideParams) (uuid.UUID, error)
	RecordSigningCheck(ctx context.Context, arg RecordSigningCheckParams) error
	RefusedByProvider(ctx context.Context, tenantID uuid.UUID) ([]RefusedByProviderRow, error)
	RegisterAuthMethod(ctx context.Context, name string) error
	RegisterDeliveryState(ctx context.Context, arg RegisterDeliveryStateParams) error
	RegisterPermission(ctx context.Context, arg RegisterPermissionParams) error
	RegisterShippedGrant(ctx context.Context, arg RegisterShippedGrantParams) error
	// A role Charon ships belongs to no tenant and is held in any. Its description
	// is left alone once it exists, because a deployment is allowed to change it.
	RegisterShippedRole(ctx context.Context, arg RegisterShippedRoleParams) (uuid.UUID, error)
	RegisterSignatureState(ctx context.Context, arg RegisterSignatureStateParams) error
	RegisterTransport(ctx context.Context, name string) error
	RegisterVerifier(ctx context.Context, name string) error
	RemoveSigningSecret(ctx context.Context, arg RemoveSigningSecretParams) (int64, error)
	// A replay only reopens deliveries whose destination is still routed for this
	// event's provider and still enabled. Anything else is history: the routes page
	// is the truth about where events go.
	ReplayDelivery(ctx context.Context, arg ReplayDeliveryParams) (int64, error)
	ReplayDestination(ctx context.Context, arg ReplayDestinationParams) (int64, error)
	ReplayEvent(ctx context.Context, arg ReplayEventParams) (int64, error)
	Retentions(ctx context.Context) ([]RetentionsRow, error)
	// A tenant may define a role of its own under a name Charon also ships, and
	// changing a shipped role is how that happens. Its own wins, said here rather
	// than left to whichever row the database hands back first: deciding what
	// somebody may do cannot depend on that.
	Role(ctx context.Context, arg RoleParams) (RoleRow, error)
	RoleByID(ctx context.Context, id uuid.UUID) (RoleByIDRow, error)
	RoleHasAnyGrant(ctx context.Context, roleID uuid.UUID) (bool, error)
	RoleIDByName(ctx context.Context, arg RoleIDByNameParams) (uuid.UUID, error)
	Roles(ctx context.Context, tenantID pgtype.UUID) ([]RolesRow, error)
	RouteByID(ctx context.Context, arg RouteByIDParams) (RouteByIDRow, error)
	// The state counts only take deliveries whose destination is still routed and
	// enabled, so the numbers reconcile with the routes page. What is left over is
	// reported apart as history.
	SearchEvents(ctx context.Context, arg SearchEventsParams) ([]SearchEventsRow, error)
	SetProvider(ctx context.Context, arg SetProviderParams) error
	SetRetention(ctx context.Context, arg SetRetentionParams) (int64, error)
	SetRole(ctx context.Context, arg SetRoleParams) (uuid.UUID, error)
	// Becoming one means leaving the role behind, and with it the tenant the role
	// belonged to; giving it up means being given a role again.
	SetSystemAdmin(ctx context.Context, id uuid.UUID) (int64, error)
	SetSystemAdminByEmail(ctx context.Context, email string) (int64, error)
	SignatureTotals(ctx context.Context) ([]SignatureTotalsRow, error)
	SigningFor(ctx context.Context, destinationID uuid.UUID) ([]SigningForRow, error)
	SigningSecrets(ctx context.Context, tenantID uuid.UUID) ([]SigningSecretsRow, error)
	SigningSecretsEverywhere(ctx context.Context) ([]SigningSecretsEverywhereRow, error)
	SigningSecretsFor(ctx context.Context, destinationID uuid.UUID) ([]string, error)
	StopPointingValue(ctx context.Context, arg StopPointingValueParams) error
	SystemAdmins(ctx context.Context) ([]SystemAdminsRow, error)
	TenantBySlug(ctx context.Context, slug string) (Tenant, error)
	Tenants(ctx context.Context) ([]Tenant, error)
	TenantsNamed(ctx context.Context, dollar_1 []string) ([]TenantsNamedRow, error)
	UnplanEvent(ctx context.Context, arg UnplanEventParams) error
	UnplanProvider(ctx context.Context, arg UnplanProviderParams) (int64, error)
	UnroutedProviders(ctx context.Context, tenantID uuid.UUID) ([]UnroutedProvidersRow, error)
	UnverifiedEvents(ctx context.Context, arg UnverifiedEventsParams) ([]UnverifiedEventsRow, error)
	UpdateDestination(ctx context.Context, arg UpdateDestinationParams) error
	UpdatePanelUserRole(ctx context.Context, arg UpdatePanelUserRoleParams) (int64, error)
	ValuesPointedAtTenant(ctx context.Context, tenantID uuid.UUID) ([]ValuesPointedAtTenantRow, error)
}

var _ Querier = (*Queries)(nil)
