// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const purgeEvents = `-- name: PurgeEvents :execrows
delete from inbound_event e
where e.tenant_id = $1
  and e.received_at < now() - make_interval(days => $2::int)
  and not exists (
      select 1 from delivery d
      where d.event_id = e.id and d.state = 'pending'
  )
`

type PurgeEventsParams struct {
	TenantID uuid.UUID
	Days     int32
}

// An event is only discarded once nothing is still trying to deliver it. A
// pending delivery is live work, and its age says the destination has been
// unreachable for a long time, which is a reason to look rather than to erase.
func (q *Queries) PurgeEvents(ctx context.Context, arg PurgeEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEvents, arg.TenantID, arg.Days)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeableEvents = `-- name: PurgeableEvents :one
select count(*) from inbound_event e
where e.tenant_id = $1
  and e.received_at < now() - make_interval(days => $2::int)
  and not exists (
      select 1 from delivery d
      where d.event_id = e.id and d.state = 'pending'
  )
`

type PurgeableEventsParams struct {
	TenantID uuid.UUID
	Days     int32
}

func (q *Queries) PurgeableEvents(ctx context.Context, arg PurgeableEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, purgeableEvents, arg.TenantID, arg.Days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const retentions = `-- name: Retentions :many
select id, slug, retention_days from tenant order by slug
`

type RetentionsRow struct {
	ID            uuid.UUID
	Slug          string
	RetentionDays pgtype.Int4
}

func (q *Queries) Retentions(ctx context.Context) ([]RetentionsRow, error) {
	rows, err := q.db.Query(ctx, retentions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetentionsRow{}
	for rows.Next() {
		var i RetentionsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.RetentionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRetention = `-- name: SetRetention :execrows
update tenant set retention_days = $2 where slug = $1
`

type SetRetentionParams struct {
	Slug          string
	RetentionDays pgtype.Int4
}

func (q *Queries) SetRetention(ctx context.Context, arg SetRetentionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRetention, arg.Slug, arg.RetentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
