// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signing.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSigningSecret = `-- name: AddSigningSecret :exec
insert into signing_secret (tenant_id, destination_id, reference)
values ($1, $2, $3)
on conflict (destination_id, reference) do nothing
`

type AddSigningSecretParams struct {
	TenantID      uuid.UUID
	DestinationID uuid.UUID
	Reference     string
}

func (q *Queries) AddSigningSecret(ctx context.Context, arg AddSigningSecretParams) error {
	_, err := q.db.Exec(ctx, addSigningSecret, arg.TenantID, arg.DestinationID, arg.Reference)
	return err
}

const destinationsWithoutSigning = `-- name: DestinationsWithoutSigning :many
select d.id, d.name, count(r.id) as routes
from destination d
left join route r on r.destination_id = d.id
where d.tenant_id = $1 and d.enabled
  and not exists (select 1 from signing_secret s where s.destination_id = d.id)
group by d.id, d.name
having count(r.id) > 0
order by d.name
`

type DestinationsWithoutSigningRow struct {
	ID     uuid.UUID
	Name   string
	Routes int64
}

func (q *Queries) DestinationsWithoutSigning(ctx context.Context, tenantID uuid.UUID) ([]DestinationsWithoutSigningRow, error) {
	rows, err := q.db.Query(ctx, destinationsWithoutSigning, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DestinationsWithoutSigningRow{}
	for rows.Next() {
		var i DestinationsWithoutSigningRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Routes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifySigning = `-- name: NotifySigning :exec
select pg_notify('charon_signing', '')
`

func (q *Queries) NotifySigning(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifySigning)
	return err
}

const recordSigningCheck = `-- name: RecordSigningCheck :exec
insert into signing_secret_check (signing_secret_id, tenant_id, readable, detail, checked_at)
values ($1, $2, $3, $4, now())
on conflict (signing_secret_id) do update
set readable = excluded.readable,
    detail = excluded.detail,
    checked_at = excluded.checked_at
`

type RecordSigningCheckParams struct {
	SigningSecretID uuid.UUID
	TenantID        uuid.UUID
	Readable        bool
	Detail          string
}

func (q *Queries) RecordSigningCheck(ctx context.Context, arg RecordSigningCheckParams) error {
	_, err := q.db.Exec(ctx, recordSigningCheck,
		arg.SigningSecretID,
		arg.TenantID,
		arg.Readable,
		arg.Detail,
	)
	return err
}

const removeSigningSecret = `-- name: RemoveSigningSecret :execrows
delete from signing_secret
where tenant_id = $1 and destination_id = $2 and reference = $3
`

type RemoveSigningSecretParams struct {
	TenantID      uuid.UUID
	DestinationID uuid.UUID
	Reference     string
}

func (q *Queries) RemoveSigningSecret(ctx context.Context, arg RemoveSigningSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSigningSecret, arg.TenantID, arg.DestinationID, arg.Reference)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const signingFor = `-- name: SigningFor :many
select s.reference, s.created_at, c.readable, coalesce(c.detail, '') as detail, c.checked_at
from signing_secret s
left join signing_secret_check c on c.signing_secret_id = s.id
where s.destination_id = $1
order by s.created_at
`

type SigningForRow struct {
	Reference string
	CreatedAt time.Time
	Readable  pgtype.Bool
	Detail    string
	CheckedAt pgtype.Timestamptz
}

func (q *Queries) SigningFor(ctx context.Context, destinationID uuid.UUID) ([]SigningForRow, error) {
	rows, err := q.db.Query(ctx, signingFor, destinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SigningForRow{}
	for rows.Next() {
		var i SigningForRow
		if err := rows.Scan(
			&i.Reference,
			&i.CreatedAt,
			&i.Readable,
			&i.Detail,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signingSecrets = `-- name: SigningSecrets :many
select d.name as destination, s.reference, s.created_at
from signing_secret s
join destination d on d.id = s.destination_id
where s.tenant_id = $1
order by d.name, s.created_at
`

type SigningSecretsRow struct {
	Destination string
	Reference   string
	CreatedAt   time.Time
}

func (q *Queries) SigningSecrets(ctx context.Context, tenantID uuid.UUID) ([]SigningSecretsRow, error) {
	rows, err := q.db.Query(ctx, signingSecrets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SigningSecretsRow{}
	for rows.Next() {
		var i SigningSecretsRow
		if err := rows.Scan(&i.Destination, &i.Reference, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signingSecretsEverywhere = `-- name: SigningSecretsEverywhere :many
select s.id, s.tenant_id, s.reference from signing_secret s
`

type SigningSecretsEverywhereRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Reference string
}

func (q *Queries) SigningSecretsEverywhere(ctx context.Context) ([]SigningSecretsEverywhereRow, error) {
	rows, err := q.db.Query(ctx, signingSecretsEverywhere)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SigningSecretsEverywhereRow{}
	for rows.Next() {
		var i SigningSecretsEverywhereRow
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Reference); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signingSecretsFor = `-- name: SigningSecretsFor :many
select reference from signing_secret
where destination_id = $1
order by created_at
`

func (q *Queries) SigningSecretsFor(ctx context.Context, destinationID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, signingSecretsFor, destinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var reference string
		if err := rows.Scan(&reference); err != nil {
			return nil, err
		}
		items = append(items, reference)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
