// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package db

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
insert into tenant (slug, name) values ($1, $2) returning id, slug, name, created_at
`

type CreateTenantParams struct {
	Slug string
	Name string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Slug, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
delete from tenant where slug = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteTenant, slug)
	return err
}

const notifyTenants = `-- name: NotifyTenants :exec
select pg_notify('charon_tenant', '')
`

func (q *Queries) NotifyTenants(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyTenants)
	return err
}

const tenantBySlug = `-- name: TenantBySlug :one
select id, slug, name, created_at from tenant where slug = $1
`

func (q *Queries) TenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const tenants = `-- name: Tenants :many
select id, slug, name, created_at from tenant order by slug
`

func (q *Queries) Tenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, tenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
